### ISSUE TITLE
locales.txt should be removed

### ISSUE THREAD

**Issue by sam** [sam/harbor#11]
The entries should just be created at the bottom of locale.rb, getting rid of the current flat-file format.

If the Locale class could be a simplified wrapper around Java's locales that would be even better.

**Comment by fgrehm** [comment]
Shouldn't we still keep support for ruby 1.9? If thats the case we could probably reopen the issue to keep track of it :)

**Comment by sam** [comment]
Yeah, I'm not convinced of it. ;-)

Still, as mentioned in the other ticket, if you want to support it, we'll stub in a `harbor/mri` you can require. It'll take some work, but I promise not to go out of my way to break 1.9. I might even test against it as well. ;-)

**Comment by sam** [comment]
BTW, I'd rather open a new ticket than reopen closed issues if that's OK with you.

**Comment by fgrehm** [comment]
Challenge accepted!
And yes, I'm fine with opening a new ticket ;)
