### ISSUE TITLE
routes should use Method#parameters

### ISSUE THREAD

**Issue by sam** [sam/harbor#17]
Routes should use `Method#parameters` to inject wildcards into arguments when an action is called.

I should be able to do this for example:

```
# This action just echoes the parameter you provide:
get "/:echo" do |echo|
  response.puts echo
end
```

This is acheivable because Ruby 1.9 provides a `#parameters` method for `Proc` and `UnboundMethod`. It's basically bringing [Merb Action Args](http://technicalpickles.com/posts/meet-merb-action-methods-taking-arguments/) back from the dead, which were themselves inspired by [CastleProject's Simple Parameter Passing](http://docs.castleproject.org/MonoRail.Getting-Started.ashx#Simple_Parameters_11). Except this time around we don't have to use `ParseTree` since Ruby 1.9 has more robust reflection support.

**Comment by fgrehm** [comment]
Should we also map querystring parameters like `action?foo=bar` to `get "action" do |foo|`?

**Comment by sam** [comment]
Definitely. When a wildcard is parsed out of a route it should be added to `request.params`, and the `#parameters` introspection (that should be added to Action) should pull out all matching `params` from the Request.

It should **not** pass `nil` if a param isn't present. Instead we should throw a HTTP 400 (Bad Request). So any argument you expect _and don't add a default for_ is **required**.

**Comment by sam** [comment]
This was done with @fgrehm's latest pull request.
