### ISSUE TITLE
Explicitly require erubis for Tilt

### ISSUE THREAD

**Issue by sam** [sam/harbor#26]
Rescue the `LoadError` in case it's not installed, but try to require it so that the load is thread-safe and supresses the _Tilt_ warning.

**Comment by fgrehm** [comment]
I could probably handle that but I wasn't able to see the _Tilt_ warning down here with `1.3.3` using 

```
jruby 1.7.0.dev (ruby-1.9.3-p139) (2012-03-01 7dd104c) (OpenJDK 64-Bit Server VM 1.6.0_22) [linux-amd64-java]
```

i did some googling and found this check on [0.9](https://github.com/rtomayko/tilt/blob/0.9/lib/tilt.rb#L155), should we depend on `Tilt >= "1.3.3"` then?

**Comment by sam** [comment]
Hmm. I thought I was using 1.3.3. Let me double-check my setup tomorrow and get back to you (though specifying a minimum version doesn't seem like a bad idea either).

**Comment by sam** [comment]
This was closed with Buaerpauer's commit.
