### ISSUE TITLE
Automatically reload changed files?

### ISSUE THREAD

**Issue by fgrehm** [sam/harbor#28]
What do you guys think about this? We could steal some ideas from [here](http://rkh.im/code-reloading) ;)

**Comment by sam** [comment]
Definitely. I'm tired of having to be explicit about the standard stuff. And reloading in development should be the default.

**Comment by Bauerpauer** [comment]
Reloading won't be pretty w/ routing information being generated by controllers.  Would be great to have, though.

**Comment by sam** [comment]
Hmm. Good call. We'll just have to make the routing calls idempotent (they probably should be anyways).

**Comment by fgrehm** [comment]
We could probably start by reloading models + helpers and wait for the routing stuff to be ready, we might split the issue on 2 if we agree on that

**Comment by sam** [comment]
Sounds good to me.
