### ISSUE TITLE
Bring back support for Locales on MRI

### ISSUE THREAD

**Issue by fgrehm** [sam/harbor#29]
I'm up for doing this, I just need to know what methods I should implement =]

**Comment by sam** [comment]
I'll write a test. I think it's just `#country`, `#language` and `#to_s` though.

The `#to_s` would look something like this:

```
def to_s
  @to_s ||= [ country, language ].compact.join("_")
end
```

They should be read-only instances, not supporting modification after initialization. So `#initialize(country, language)` in other words.

**Comment by sam** [comment]
Fabio fixed this.
