### ISSUE TITLE
Proposal: New Route Helper - redirect

### ISSUE THREAD

**Issue by Bauerpauer** [sam/harbor#37]
``` ruby
class SomeCrazyController < Harbor::Controller
   redirect "/login", "/sessions/new"
end
```

The helper wires up a "GET" for "/login" that simply redirects to "/sessions/new".  Alternatively:

``` ruby
class SomeCrazyController < Harbor::Controller
   redirect "/login" { "/sessions/new" }
end
```

This could allow some kind of processing inside the block, from which you are to return a String or maybe a URI.

**Comment by sam** [comment]
Took me awhile to figure out why a _redirect_ and not an _alias_. But yeah, this is better for SEO.

I dig it. Though I don't care for the block-syntax. A redirect should be just that. If you want to process-then-redirect, you already have a way to do that with only marginally more typing.

**Comment by sam** [comment]
One thing to keep in mind, I do think both matcher and target routes should follow the same routing logic as regular routes WRT relative vs absolute routes. ie:

``` ruby
class SessionController < Harbor::Controller
  # Redirect the rooted /login route to /session/new using a relative target.
  redirect "/login", "new"
end
```

**Comment by sam** [comment]
Thoughts?

**Comment by Bauerpauer** [comment]
Sure, the simple redirect works for me.  It should issue a 301 (Permanent).
