### ISSUE TITLE
Harbor Console should be added to the harbor bin

### ISSUE THREAD

**Issue by sam** [sam/harbor#6]
Running `harbor console [ environment ]` from the root of your application should drop you into an irb session in your application for that environment.

The environment portion should just be passed through to Harbor::Configuration, which will address loading up the appropriate environment.

**Comment by fgrehm** [comment]
What about switching to [Pry](https://github.com/pry/pry) instead of using plain IRB? I've been using it for almost an year now and it's been awesome :-)

**Comment by sam** [comment]
I really hate adding additional external dependencies we don't control. And Pry adds a number of them itself as well.

On the other hand it does look really cool. ;-)

I dunno. Any thoughts @Bauerpauer?

**Comment by fgrehm** [comment]
There is a workaround that people could do on their projects like some do in rails with this http://www.dotnetguy.co.uk/post/2011/08/23/replace-the-rails-console-with-pry, if we could avoid the whole `silence_warnings` block and do something like the code below would be great :-)

``` ruby
# inside config/development.rb
require 'pry'
config.console = Pry
```

**Comment by sam** [comment]
Sounds aces to me. We can leave that commented out in the `env/default.rb` and the generated `Gemfile` to make it easy for peeps as well.

Though I think something like `config.console = Harbor::Console::Pry` instead. Which is just a stub to `require "pry"` for you when called. The default would be `config.console = Harbor::Console::IRB`. So neither would be required until called, but the setup could live in `env/default.rb`.

Hopefully that all makes sense. I'll add it tonight.

**Comment by fgrehm** [comment]
Awesome, a lot cleaner than `silence_warnings` :P

**Comment by sam** [comment]
Finally done in: f7512851dff02bbc45c2428013f2e9eb20614026.

The IRB console works. The `Harbor::Consoles::Pry` is present, but untested. I'll work on that now.
