### ISSUE TITLE
Proposal: Serve static files on development mode

### ISSUE THREAD

**Issue by fgrehm** [sam/harbor#63]
We should be able to serve JS, CSS, imgs, etc... through `harbor server` while developing right? ;-)

**Comment by fgrehm** [comment]
I'm going ahead to implement this but I'm wondering how we'll deal with ports / gem's assets in production mode without having to include their public paths into server's configuration

any thoughts?

**Comment by sam** [comment]
Pulled in Pull Request #66. So closing this out.
